version: '3'

services:
  ridik-api:
    build: .
    # command: nodemon index.js
    restart: always
    ports:
      - '3000:3000'
      - '3001:3001'
    volumes:
      - .:/app
    env_file:
      - .env